### ISSUE TITLE
How to install it in Google collab?

### ISSUE THREAD

**Issue by CombainerA19** [serpotapov/Kohya_ss-GUI-LoRA-Portable#1]
Hello! Nice work! 
How this version can be installed in Automatic1111 UI Google Collab?

**Comment by reTYPise** [comment]
> Привет! Хорошая работа! Как эту версию можно установить в Automatic1111 UI Google Collab?

https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb
