### ISSUE TITLE
Sample папка

### ISSUE THREAD

**Issue by Nixellion** [serpotapov/Kohya_ss-GUI-LoRA-Portable#11]
Я по поводу удаления папки sample которое надо каждый раз не забывать делать.

Может быть есть смысл поправить код что бы эта папка не создавалась или всегда удалялась? Этот вопрос рассматривался? Или будут проблемы с обновлениями? Или она все таки нужна для каких то задач?

Во всем коде я нашел только здесь создание этой папки, выглядит как будто не сложно это отключить )

`sampler_gui.py`

```python
    output_dir = os.path.join(output_dir, 'sample')

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
```

**Comment by serpotapov** [comment]
Приветствую 🖐
Отошлите Вашу находку в это репо ➜ https://github.com/bmaltais/kohya_ss
