### ISSUE TITLE
Ошибка при Train

### ISSUE THREAD

**Issue by hack337-LZT** [serpotapov/Kohya_ss-GUI-LoRA-Portable#13]
OS: Win 10 
GPU: RTX 3050
Log:
```
Loading config...
Folder 100_SL: 112 images found
Folder 100_SL: 11200 steps
max_train_steps = 5600
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="C:/stable-diffusion-webui-master/models/Stable-diffusion/deliberate_v2.safetensors" --train_data_dir="C:\Users\serg\Desktop\py_tg_img\aaa\" --resolution=512,512 --output_dir="C:\Users\serg\Desktop\py_tg_img\aaa\" --logging_dir="" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="SL" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2" --max_train_steps="5600" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
Traceback (most recent call last):
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 760, in <module>
    train(args)
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 117, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\library\config_util.py", line 375, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\library\train_util.py", line 981, in __init__
    assert resolution is not None, f"resolution is required / resolution（解像度）指定は必須です"
AssertionError: resolution is required / resolution（解像度）指定は必須です
Traceback (most recent call last):
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "K:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['K:\\Kohya_ss-GUI-LoRA-Portable-main\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:/stable-diffusion-webui-master/models/Stable-diffusion/deliberate_v2.safetensors', '--train_data_dir=C:\\Users\\serg\\Desktop\\py_tg_img\\aaa" --resolution=512,512 --output_dir=C:\\Users\\serg\\Desktop\\py_tg_img\\aaa"', '--logging_dir=', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=SL', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=5600', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
```

**Comment by nishichi** [comment]
Та же проблема

**Comment by nishichi** [comment]
> OS: Win 10 GPU: RTX 3050 Log:
> 
> ```
> Loading config...
> Folder 100_SL: 112 images found
> Folder 100_SL: 11200 steps
> max_train_steps = 5600
> stop_text_encoder_training = 0
> lr_warmup_steps = 0
> accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="C:/stable-diffusion-webui-master/models/Stable-diffusion/deliberate_v2.safetensors" --train_data_dir="C:\Users\serg\Desktop\py_tg_img\aaa\" --resolution=512,512 --output_dir="C:\Users\serg\Desktop\py_tg_img\aaa\" --logging_dir="" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="SL" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2" --max_train_steps="5600" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale
> prepare tokenizer
> Use DreamBooth method.
> Traceback (most recent call last):
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 760, in <module>
>     train(args)
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 117, in train
>     train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\library\config_util.py", line 375, in generate_dataset_group_by_blueprint
>     dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\library\train_util.py", line 981, in __init__
>     assert resolution is not None, f"resolution is required / resolution（解像度）指定は必須です"
> AssertionError: resolution is required / resolution（解像度）指定は必須です
> Traceback (most recent call last):
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
>     args.func(args)
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
>     simple_launcher(args)
>   File "K:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['K:\\Kohya_ss-GUI-LoRA-Portable-main\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:/stable-diffusion-webui-master/models/Stable-diffusion/deliberate_v2.safetensors', '--train_data_dir=C:\\Users\\serg\\Desktop\\py_tg_img\\aaa" --resolution=512,512 --output_dir=C:\\Users\\serg\\Desktop\\py_tg_img\\aaa"', '--logging_dir=', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=SL', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=5600', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
> ```

помогло исправление пути к модели, обратите внимание на / и \
