### ISSUE TITLE
При нажатие Train ничего не происходит

### ISSUE THREAD

**Issue by gregtorn** [serpotapov/Kohya_ss-GUI-LoRA-Portable#15]
Установил, Настроил все для тренировки Lora. Жму Train и ничего не происходит от слова совсем.  Никаких ошибок. Вообще никакой реакции на нажатие.
OS: Win 10
GPU: RTX 3070

**Comment by serpotapov** [comment]
Приветствую 🖐
Лучше задать вопрос со скриншотами на сервере в Discord.
https://discord.gg/xpuct
