### ISSUE TITLE
Отсутствуют  text encoder learning rate / unet learning rate / network rank

### ISSUE THREAD

**Issue by wrappan** [serpotapov/Kohya_ss-GUI-LoRA-Portable#16]
Добрый день.
В видео есть во вкладке Training parameters
есть строка настроек с  text encoder learning rate / unet learning rate / network rank
В портабл версии они у меня не отображаются. Ее просто нет.
Скажите в чем может быть причина, в остальном все работает как в видео.
Спасибо

**Comment by serpotapov** [comment]
Добрый 🖐
Перейдите, пожалуйста, в правильную вкладку – Dreambooth LoRA.
Или запускайте webui-lora-only.cmd, чтобы запускать сразу правильный UI и не отвлекаться.

**Comment by wrappan** [comment]
Мерси! Вот это я слепой )
