### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by perkuschina** [serpotapov/Kohya_ss-GUI-LoRA-Portable#19]
Добрый день. После нажатия кнопки "Training Model" выдает следующее
![2023-05-02_153222](https://user-images.githubusercontent.com/127803353/235607155-e6d9340b-df70-4a74-aa71-82d400303c56.jpg)
Подскажите пожалуйста . как это исправить? Спасибо.

**Comment by Ptiolerwud** [comment]
Такая же пробелма как выше

**Comment by serpotapov** [comment]
Приветствую 🖐
Проверьте, что пути к модели правильные.
По проблемам лучше обращаться в Discord ➜ https://discord.gg/xpuct

**Comment by Ptiolerwud** [comment]
> Приветствую 🖐 Проверьте, что пути к модели правильные. По проблемам лучше обращаться в Discord ➜ https://discord.gg/xpuct
путь без пробелов и кириллицы(((
![image](https://user-images.githubusercontent.com/132476183/235966054-2720193c-6f5c-4622-a3ed-40daa9ac398e.png)
