### ISSUE TITLE
Пайторчь не супортит девайс Nvidia RTX2070 Super

### ISSUE THREAD

**Issue by AndreySkyFoxSidorov** [serpotapov/Kohya_ss-GUI-LoRA-Portable#3]
Чтото Ругаеться на то что Пайторчь не супортит девайс 
**err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device.**
Хотя StableDiffusion нормально работает, и обучение hypernetworks на нем нормально работают. 

Лог:

Folder 100_Marina: 4300 steps
max_train_steps = 2150
stop_text_encoder_training = 0
lr_warmup_steps = 215
accelerate launch --num_cpu_threads_per_process=2 "train_db.py" --pretrained_model_name_or_path="D:/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion/deliberate_v2.safetensors" --train_data_dir="D:/StableDiffusion/train" --resolution=512,512 --output_dir="D:/StableDiffusion/train" --logging_dir="" --save_model_as=safetensors --output_name="Marina" --max_data_loader_n_workers="1" --learning_rate="0.0001" --lr_scheduler="constant" --lr_warmup_steps="215" --train_batch_size="2" --max_train_steps="2150" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale
prepare tokenizer
Downloading (…)olve/main/vocab.json: 100%|██████████████████████████████████████████| 961k/961k [00:00<00:00, 1.72MB/s]
Downloading (…)olve/main/merges.txt: 100%|██████████████████████████████████████████| 525k/525k [00:00<00:00, 1.09MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████| 389/389 [00:00<00:00, 390kB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 905/905 [00:00<00:00, 909kB/s]
prepare images.
found directory D:\StableDiffusion\train\100_Marina contains 43 image files
4300 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "D:\StableDiffusion\train\100_Marina"
    image_count: 43
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    is_reg: False
    class_tokens: Marina
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 2391.60it/s]
prepare dataset
prepare accelerator
Traceback (most recent call last):
  File "D:\StableDiffusion\ss-GUI-LoRA\train_db.py", line 364, in <module>
    train(args)
  File "D:\StableDiffusion\ss-GUI-LoRA\train_db.py", line 75, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "D:\StableDiffusion\ss-GUI-LoRA\library\train_util.py", line 1984, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "D:\StableDiffusion\ss-GUI-LoRA\venv\lib\site-packages\accelerate\accelerator.py", line 370, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "D:\StableDiffusion\ss-GUI-LoRA\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\StableDiffusion\ss-GUI-LoRA\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\StableDiffusion\ss-GUI-LoRA\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\StableDiffusion\ss-GUI-LoRA\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\StableDiffusion\ss-GUI-LoRA\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\StableDiffusion\ss-GUI-LoRA\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\StableDiffusion\\ss-GUI-LoRA\\venv\\Scripts\\python.exe', 'train_db.py', '--pretrained_model_name_or_path=D:/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion/deliberate_v2.safetensors', '--train_data_dir=D:/StableDiffusion/train', '--resolution=512,512', '--output_dir=D:/StableDiffusion/train', '--logging_dir=', '--save_model_as=safetensors', '--output_name=Marina', '--max_data_loader_n_workers=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=215', '--train_batch_size=2', '--max_train_steps=2150', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by serpotapov** [comment]
Поменяйте bf16 на fp16
