### ISSUE TITLE
Error during reinstallation

### ISSUE THREAD

**Issue by LeRoDee1** [serpotapov/Kohya_ss-GUI-LoRA-Portable#9]
My LORA stopped working for some reason, so I decided to reinstall it, but then I encountered this error.
[Моя ЛОРА по какой-то причине перестала запускаться и я решил её переустановить, в следствии чего я столкнулся с такой ошибкой]
![image](https://user-images.githubusercontent.com/129805534/229649999-8d8b793d-a5d8-440b-a983-14b31283a912.png)
What could be the reason?
[В чём может быть причина?]

**Comment by LeRoDee1** [comment]
I found the error!
When downloading using the command 'git clone "link" ', a file named "Kohya_ss-GUI-LoRA-Portable" is downloaded, but when downloading the zip file, a file named "Kohya_ss-GUI-LoRA-Portable-main" is downloaded. Because of this, I couldn't solve my problem

**Comment by serpotapov** [comment]
Hey 🖐
Please follow the exact instructions.
You don't need git clone, just download ZIP and just **double click** on firstrun.cmd.
